name: parse-documents-fast-stack

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: parse-documents-fast:1.2.0
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
          - pdf_internal_network  # Red privada exclusiva para App <-> Mongo
          - fast_pdf_network       # Red externa compartida con Traefik
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pdf-app.rule=Host(`api.pdfmanager.local`)"
        - "traefik.http.routers.pdf-app.entrypoints=https"
        - "traefik.http.routers.pdf-app.tls=true"
        - "traefik.http.services.pdf-app.loadbalancer.server.port=8000" 

networks:
    pdf_internal_network:
      driver: bridge
    fast_pdf_network:
      external: true