# --------------------------------------------------------------
# --- Plantilla estandar: Para desarrollo local con MongoDB ---
# --------------------------------------------------------------

services:
  mongodb:
    image: mongo:7-jammy
  # ports:
  #  - "27017:27017"
    networks:
      - pdf_internal_network  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/?authSource=admin
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    networks:
      - pdf_internal_network
      - fast_pdf_network 

volumes:
  mongodb_data: